### ISSUE TITLE
x3p files exported from the microscope don't show the image

### ISSUE THREAD

**Issue by heike** [talenfisher/fix3p#6]
fix3p.bundle.js?v=113:27 Uncaught (in promise) TypeError: Cannot read property 'innerHTML' of null
    at XMLDocument.Document.get (fix3p.bundle.js?v=113:27)
    at XMLDocument.Document.getFloat (fix3p.bundle.js?v=113:27)
    at M.setupIncrements (fix3p.bundle.js?v=113:27)
    at new M (fix3p.bundle.js?v=113:27)
    at R.extract (fix3p.bundle.js?v=113:27)

**Comment by talenfisher** [comment]
I've just released a patch, v0.1.21, which should remedy this.  Looked like an issue when not all increments are included (the Z increment is missing in some of those, but it isn't needed). 

I tested against several files in Hamby Set 224 Clone, Test Set 1.  Please let me know if the issue is still occurring for you, and if so, which files are having problems!

**Comment by talenfisher** [comment]
Heike, is this still occurring?

**Comment by heike** [comment]
I believe it's fixed! Thanks!

**Comment by talenfisher** [comment]
No problem!
